### ISSUE TITLE
How to cross compile a node application for arm architecture?

### ISSUE THREAD

**Issue by HmidiSlim** [openpipekit/opk-cli--dat#2]
I create a node application which need to extend from a C program a module node.I used for that SWIG(Simple Wrapper Interface Generator) ,then I run 
node-gyp configure 
node-gyp build 
the app runs on my PC.when I tried to cross compile it for arm architecture,I run
node-configure --arch=arm 
node-gyp build 
I got this message:
gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.38 | linux | arm
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/slim/a/build'
make: **\* No rule to make target '../../../.node-gyp/0.10.38/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/home/slim/a/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.0.4
gyp ERR! command "node" "/usr/bin/node-gyp" "build"
gyp ERR! cwd /home/slim/a
gyp ERR! node -v v0.10.38
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok

**Comment by dogi** [comment]
@HmidiSlim I suggest you ask your question on IRC [#node.js](http://webchat.freenode.net/?channels=node.js)

Anyway opk-cli--dat is not a cross compiled project - we are installing dat directly on a raspberry pi,
also so far I have not seen any relation to dat or openpipekit
